version: "3.9"

services:

    redis_pubsub:
        build:
            context: .
            dockerfile: Dockerfile
        image: share_market-image
        container_name: ecom_worker
        depends_on:
            - postgres
            - redis
        # restart: always
        volumes:
            - ./src:/code/src
        entrypoint:
            - python
            - /code/src/entrypoint/redis_eventconsumer.py

    api:
        build:
            context: .
            dockerfile: Dockerfile
        image: share_market_image
        container_name: ecom_app
        depends_on:
            - redis_pubsub
            - postgres
        # restart: always
        volumes:
            - ./:/code/

        command: [ "python", "entrypoint/main.py" ]
        ports:
            - "8000:8000"

    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: app
        container_name: ecom_db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - "12345:5432"

    redis:
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"

volumes:
  postgres_data:

