INVALID_EMAIL_PASSWORD = "Could not verify, Wrong email or password"
MISSING_PARAMS = "Could not verify, Either email or Password is Missing"
DATA_NOT_FOUND = "Data not found"
USER_NOT_ACTIVE = "Please Activate your account"
PASSWORD_INCORRECT = "Password is incorrect"
PASSWORD_MISMATCHED = "Password did not match"
REDIS_CONNECTION_NOT_ESTABLISHED = "redis connection is not started"
USER_DOES_NOT_EXIST = "User does not exist"
OTP_NOT_FOUND = "OTP is not found"
OTP_MISMATCHED = "OTP has mismatched"
DUPLICATION_SELLER_ID = "Seller Id Already Exist"
DUPLICATION_SELLER_NAME = "Seller Name Already Exist"
DUPLICATION_SELLER_PHONE = "Seller Phone Already Exist"
DUPLICATION_COMPANY_NAME = "Company Name Already Exist"
DUPLICATION_COMPANY_SYMBOL = "Company Symbol Already Exist"
DUPLICATION_SHAREHOLDER_NAME = "Shareholder Name Already Exist"
DUPLICATION_CRN_NUMBER = "CRN Number Already Exist"
SHAREHOLDER_ID_NOT_FOUND = "shareholder with id not found "
HOLDING_TRANSACTION_STATUS_CHANGED_SUCCESSFULLY = (
    "holding transaction status changed successfully"
)
ID_NOT_PROVIDED = "Provide Shareholder ID"
DATE_NOT_PROVIDED = "date not provided"
PHONE_NUMBER_INVALID = "provide valid phone number"
